### PR TITLE
refactor: Create mono repo structure

### PR DESCRIPTION
**Pull request by CarsonCook**
# Description

Creates a mono repo structure, currently only using the commonbot module.

Linked to #46

## Type of change

Please delete options that are not relevant.

- [ ] (fix) Bug fix (non-breaking change which fixes an issue)
- [ ] (feat) New feature (non-breaking change which adds functionality)
- [ ] (docs) Change in a documentation
- [x] (refactor) Refactor the code 
- [ ] (chore) Chore, repository cleanup, updates the dependencies.
- [ ] (BREAKING CHANGE or !) Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas. In JS I did provide JSDoc
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The tests in the area I was working on leverage nested `describe` blocks where appropriate
- [ ] Any dependent changes have been merged and published in downstream modules

For more details about how should the code look like read the [Contributing guideline](https://github.com/zowe/zowe-chat/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by XuehongBJLiang** [comment]
Hi @CarsonCook  I suggest to remove package-lock.json  and add to .gitignore

**Comment by CarsonCook** [comment]
> Hi @CarsonCook I suggest to remove package-lock.json and add to .gitignore

Hi @XuehongBJLiang, my understanding is that `package-lock.json` should be committed as this ensures that the exact same dependencies can be installed by developers and automation. Documentation from npm strongly recommends to commit `package-lock.json` https://docs.npmjs.com/cli/v6/configuring-npm/package-locks

**Comment by MarkAckert** [comment]
This is the zowe-cli dependency lock: https://github.com/zowe/zowe-cli/blob/master/npm-shrinkwrap.json

**Review by Wusong-Fang — APPROVED** [review]

**Comment by XuehongBJLiang** [comment]
> > Hi @CarsonCook I suggest to remove package-lock.json and add to .gitignore
> 
> Hi @XuehongBJLiang, my understanding is that `package-lock.json` should be committed as this ensures that the exact same dependencies can be installed by developers and automation. Documentation from npm strongly recommends to commit `package-lock.json` https://docs.npmjs.com/cli/v6/configuring-npm/package-locks

Thanks for sharing.

**Review by XuehongBJLiang — APPROVED** [review]

**Pull request merged**
